#!/bin/sh
#
#           Author: Erick Gallesio [eg@essi.fr]
#    Creation date: 19-Nov-2003 21:04 (eg)
# Last file update: 19-Nov-2003 22:29 (eg)


function usage()
{
    cat <<EOF
Usage: skribe-config [OPTIONS]
Options:
	[--prefix | -p]		Prefix that was given during the build
	[--version | -v]	Version of Skribe that is installed
	[--skr-dir | -k]	Display the skr directory location
	[--extension-dir | -e]	Display the extension directory location
	[--doc-dir | -d]	Display the documentation directory location
	[--emacs-dir | -m]	Display the emacs directory location
        [--scheme | -s]         Display the Scheme systeme used
	[--help | -h | -?]	Show a list of options
EOF
    exit $1
}


if test $# -eq 0; then
    usage 1 1>&2
fi

while test $# -gt 0; do
    case $1 in
	--prefix|-p)
	    echo /usr/local
	    ;;
	--version|-v)
	    echo 1.2d
	    ;;
	--extension-dir|-e) 
	    echo /usr/local/share/skribe/extensions
	    ;;
	--skr-dir|-k) 
	    echo /usr/local/share/skribe/1.2d/skr
	    ;;
	--doc-dir|-d) 
	    echo /usr/local/doc/skribe-1.2d
	    ;;
	--emacs-dir|-m) 
	    echo /users/serrano/emacs/site-lisp/bigloo
	    ;;
	--scheme|-s) 
	    echo bigloo
	    ;;
	--help|-h|-\?)
	    usage 0 1>&2
	    ;;
	*)
	    echo "bad option $1" 1>&2
	    usage 1 1>&2
	    ;;
    esac
    shift
done
exit 0

