#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/scribe/autoconf/blibdir                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Tue Jan 12 14:53:33 1999                          */
#*    Last change :  Wed Aug  7 21:41:48 2002 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Find out the directory where Bigloo library is read.             */
#*=====================================================================*/
bigloo=bigloo

#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;
    --bigloo=*|-bigloo=*)
      bigloo="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

#*---------------------------------------------------------------------*/
#*    We spawn a bigloo process to check its version number            */
#*---------------------------------------------------------------------*/
$bigloo -q -eval "(begin (print *ld-library-dir*) (exit 0))"

exit 0


