#!/bin/sh
#*=====================================================================*/
#*    serrano/prgm/project/bglk/autoconf/getbversion                   */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Tue Jan 12 14:33:21 1999                          */
#*    Last change :  Mon May 22 10:47:46 2000 (serrano)                */
#*    -------------------------------------------------------------    */
#*    Get the current bigloo version (with the level)                  */
#*=====================================================================*/

bigloo=bigloo
 
#*---------------------------------------------------------------------*/
#*    We parse the arguments                                           */
#*---------------------------------------------------------------------*/
while : ; do
  case $1 in
    "")
      break;;
    --bigloo=*|-bigloo=*)
      bigloo="`echo $1 | sed 's/^[-a-z]*=//'`";;

    --version=*|-version=*)
      version="`echo $1 | sed 's/^[-a-z]*=//'`";;

    -*)
      echo "Unknown option \"$1\", ignored" >&2;;
  esac
  shift
done

#*---------------------------------------------------------------------*/
#*    We spawn a bigloo process to check its version number            */
#*---------------------------------------------------------------------*/
$bigloo -q -eval "(begin (print *bigloo-version*) (exit 0))"
